### ISSUE TITLE
Implement: 'info' command, get info about the target computer

### ISSUE THREAD

**Issue by EinBaum** [EinBaum/Totally-Not-A-Virus#36]
Information:

* [x] List of usernames + custom defined names
* [x] Computer name
* [x] OS version
* [x] List of programs
* Hardware specs
  * [x] CPU
  * [x] RAM
  * [x] GPU 
* [x] Runtime usage (CPU usage, RAM usage)
* [x] Time, Timezone
* [x] Processes/Running programs (taskmgr)

**Comment by Nuke928** [comment]
@EinBaum Data layout?

**Comment by EinBaum** [comment]
@Nuke928 

entityname:value;value;value;
entityname:value;

(entities separated by line breaks)
(values separated by semicolons)

**Comment by Nuke928** [comment]
Is this enough now?

**Comment by EinBaum** [comment]
Looks great, we'll reopen this issue if we have some more ideas.

**Comment by EinBaum** [comment]
Audio Devices
