### ISSUE TITLE
Set Unicode as default setting IN PROJECT PROPERTIES

### ISSUE THREAD

**Issue by EinBaum** [EinBaum/Totally-Not-A-Virus#46]
Setting Unicode using a define will override project settings. It will be impossible to disable it.

**Comment by Nuke928** [comment]
http://www.cmake.org/pipermail/cmake/2008-November/025596.html

**Comment by Nuke928** [comment]
https://github.com/EinBaum/Totally-Not-A-Virus/commit/15d438930c025cc809a19c3f0480b2655a7801ad
