### ISSUE TITLE
Lock the file from the user

### ISSUE THREAD

**Issue by UnrealHero** [EinBaum/Totally-Not-A-Virus#49]
Lock the file from the user with a sub-program so he can't see it. Auto-destroy the locker so there its no evidence.

**Comment by EinBaum** [comment]
@UnrealHero What exactly do you mean by locking a file? Can you link an example please?

**Comment by UnrealHero** [comment]
Here its an example of locking folders, in case you include more files.
https://www.youtube.com/watch?v=tWCdSIKyxHg

**Comment by EinBaum** [comment]
This script renames the folder and sets "hidden" and "system" flags.

We already set those flags here:
https://github.com/EinBaum/Totally-Not-A-Virus/blob/72601b532b83e5ad09df375f5640dfa089c49c68/Client/src/Installer.cpp#L110

By the way, this type of "locking" shown in the video is hilarious. Nothing is preventing you from accessing that folder (just need to setup explorer to view hidden files), the batch file is editable (you can see what it's doing) and the "password" is stored in plain text.

**Comment by UnrealHero** [comment]
it was the first video i found. ^^

**Comment by UnrealHero** [comment]
Sorry for requesting something that you already made, you can delete the issues.
